name: Preview Release

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: bun run build
      - run: bun x pkg-pr-new publish
